### PR TITLE
Get w building on Linux

### PR DESCRIPTION
**Pull request by zploskey**
Call to extend was missing parentheses.This fixes issue #5.

Also fix some compile-time errors on Linux.

### CODE REVIEW

**Comment by zploskey** [comment]
There are still two compilation errors that need to be sorted out:

```
In file included from persistence/p.cpp:1:
In file included from ./persistence/p.hpp:17:
In file included from ./persistence/record_type_builder.hpp:10:
./persistence/record_as_structured_data.hpp:120:47: error: implicit instantiation of undefined
      template 'wayward::data_franca::Adapter<long, void>'
    struct Adapter<persistence::PrimaryKey> : Adapter<int64_t> {
                                              ^
./wayward/support/data_franca/adapter.hpp:56:58: note: template is declared here
    template <typename T, typename Enable = void> struct Adapter;
                                                         ^
In file included from persistence/p.cpp:1:
In file included from ./persistence/p.hpp:17:
In file included from ./persistence/record_type_builder.hpp:10:
./persistence/record_as_structured_data.hpp:121:84: error: type 'Adapter<int64_t>' is not a
      direct or virtual base of 'wayward::data_franca::Adapter<persistence::PrimaryKey>'
  ...key, Bitflags<Options> o = Options::None) : Adapter<int64_t>(key.id) {}
                                                 ^~~~~~~~~~~~~~~~
```

**Comment by zploskey** [comment]
The project now successfully builds on Ubuntu 15.04 with Clang 3.6.

**Comment by Cir0X** [comment]
Is it possible to run the project on an raspberry pi?
I'm currently using Raspbian but I'm facing a problem with libpq:

```
scons: Reading SConscript files ...
Package libpq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpq' found
Package libpq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpq' found
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__':
  File "/home/pi/projects/wtest/w/SConstruct", line 202:
    w_dev = WaywardProgram(env_with_ws, 'w_dev', w_util_sources, rpaths = ['.'])
  File "/home/pi/projects/wtest/w/wayward_build.py", line 62:
    program = WaywardInternalProgram(environment, target_name, source, rpaths)
  File "/home/pi/projects/wtest/w/wayward_build.py", line 55:
    libs.extend['event', 'event_pthreads', 'pq', 'unwind']
scons -j8  5,74s user 0,49s system 82% cpu 7,564 total`
```

I´ve installed `libpq-dev`and `libpq5`
